### PR TITLE
Enable the setting of width, height and bitrate when compressing videos

### PR DESCRIPTION
**Pull request by Pururun**
It seems like this should be possible to do.

### CODE REVIEW

**Comment by josinaldobarbosa** [comment]
UP!, this feature is very important

**Comment by josinaldobarbosa** [comment]
Up!

**Comment by Tourenathan-G5organisation** [comment]
@larrytech7 please take a look at this PR

**Comment by Tourenathan-G5organisation** [comment]
Thanks @Pururun & @josinaldobarbosa for contributing. 
I going through your PR and will merge if all is well.

**Pull request merged**
